#!/usr/bin/env python3
"""
Web 导出脚本 — godot-v1 模板
调用 Godot headless 导出 Web 产物到 html5/ 目录

用法：
  python scripts/export_web.py [--godot /path/to/godot]
"""
import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent
HTML5_DIR = PROJECT_ROOT / "html5"
EXPORT_PRESETS = PROJECT_ROOT / "export_presets.cfg"
GODOT_ENV_KEY = "GODOT4_PATH"
GODOT_IGNORE_DIRS = ("exports", "reports", ".runtime", "tools", "html5")

sys.path.insert(0, str(PROJECT_ROOT / "scripts"))
from godot_locator import find_godot  # noqa: E402


def ensure_godot_ignored_process_dirs() -> None:
    for name in GODOT_IGNORE_DIRS:
        directory = PROJECT_ROOT / name
        directory.mkdir(parents=True, exist_ok=True)
        marker = directory / ".gdignore"
        if not marker.exists():
            marker.write_text("# Generated by scripts/export_web.py\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Godot Web 导出")
    parser.add_argument("--godot", default="", help="Godot 可执行文件路径")
    parser.add_argument("--json", action="store_true", help="JSON 输出模式")
    args = parser.parse_args()

    json_mode = args.json

    def log(level: str, msg: str) -> None:
        if not json_mode:
            print(f"[{level}] {msg}")

    godot = find_godot(args.godot)
    if not godot:
        msg = (
            "未找到 Godot 可执行文件。请先运行 init.cmd 解包 tools/ 中的 portable Godot，"
            f"或设置环境变量 {GODOT_ENV_KEY}，或使用 --godot 参数"
        )
        if json_mode:
            print(json.dumps({"status": "error", "message": msg}, ensure_ascii=False))
        else:
            print(f"[FAIL] {msg}")
        return 1

    log("OK", f"使用 Godot：{godot}")

    if not EXPORT_PRESETS.exists():
        msg = "export_presets.cfg 不存在，无法导出"
        if json_mode:
            print(json.dumps({"status": "error", "message": msg}, ensure_ascii=False))
        else:
            print(f"[FAIL] {msg}")
        return 1

    ensure_godot_ignored_process_dirs()
    HTML5_DIR.mkdir(parents=True, exist_ok=True)
    output_path = HTML5_DIR / "index.html"

    log("INFO", f"开始导出 → {output_path}")

    result = subprocess.run(
        [godot, "--headless", "--export-release", "Web", str(output_path)],
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        cwd=PROJECT_ROOT,
    )

    if result.returncode != 0:
        err = (result.stderr or result.stdout or "未知错误").strip()
        msg = f"导出失败：{err}"
        if json_mode:
            print(json.dumps({"status": "error", "message": msg}, ensure_ascii=False))
        else:
            print(f"[FAIL] {msg}")
            print("[NEXT] 请确认已在 Godot 编辑器安装 Web Export Templates")
            print("[NEXT] Editor → Manage Export Templates → Download")
        return 1

    # 验证产物
    if not output_path.exists():
        msg = "导出命令成功但未找到 html5/index.html，请检查 export_presets.cfg"
        if json_mode:
            print(json.dumps({"status": "error", "message": msg}, ensure_ascii=False))
        else:
            print(f"[FAIL] {msg}")
        return 1

    files = list(HTML5_DIR.iterdir())
    log("OK", f"导出完成，共 {len(files)} 个文件 → {HTML5_DIR}")

    if json_mode:
        print(json.dumps({
            "status": "ok",
            "output_dir": str(HTML5_DIR),
            "file_count": len(files),
        }, ensure_ascii=False))

    log("NEXT", "运行 python scripts/run_web_preview.py --open 启动本地预览")
    log("NEXT", "运行 python scripts/package_dist.py 打包部署 zip")
    return 0


if __name__ == "__main__":
    sys.exit(main())
