#!/usr/bin/env python3
"""Build a native Windows playable package from the Godot project."""
from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
import zipfile
from pathlib import Path
from typing import Any

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
if hasattr(sys.stderr, "reconfigure"):
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")

PROJECT_ROOT = Path(__file__).resolve().parent.parent
EXPORTS_DIR = PROJECT_ROOT / "exports"
DEFAULT_GAME_NAME = "T8-demo"
DEFAULT_OUT_DIR = EXPORTS_DIR / "T8-demo-windows"
DEFAULT_ZIP = EXPORTS_DIR / "T8-demo-windows.zip"
TEMPLATE_ENTRY = "templates/windows_release_x86_64.exe"
EXPORT_PRESET = "Windows Desktop"
WINDOWS_TEMPLATE = PROJECT_ROOT / ".runtime" / "export_templates" / "windows_release_x86_64.exe"
GODOT_IGNORE_DIRS = ("exports", "reports", ".runtime", "tools", "html5")

sys.path.insert(0, str(PROJECT_ROOT / "scripts"))
from godot_locator import find_godot  # noqa: E402


README_CONTENT = """T8-demo Windows 可游玩包

使用方式：
1. 先完整解压 zip。
2. 双击 T8-demo.exe 启动游戏。
3. T8-demo.exe 和 T8-demo.pck 必须放在同一个目录，不要只单独复制 exe。

说明：
- 这是 Godot 原生 Windows x86_64 包，不需要浏览器，也不需要启动游戏.cmd。
- 如果 Windows 安全提示拦截，选择“更多信息”后再运行，或把压缩包放到可信目录后重新解压。
"""


README_CONTENT = """T8-demo Windows 可游玩包

使用方式：
1. 先完整解压 zip。
2. 双击 T8-demo.exe 启动游戏。
3. T8-demo.exe 和 T8-demo.pck 必须放在同一个目录，不要只单独复制 exe。

说明：
- 这是 Godot 原生 Windows x86_64 包，不需要浏览器，也不需要启动游戏.cmd。
- 如果 Windows 安全提示拦截，选择“更多信息”后再运行，或把压缩包放到可信目录后重新解压。
"""


def _print(result: dict[str, Any], json_mode: bool) -> None:
    if json_mode:
        print(json.dumps(result, ensure_ascii=False, indent=2))
        return
    if result.get("status") == "ok":
        print(f"[OK] Windows playable directory: {result['out_dir']}")
        print(f"[OK] zip: {result['zip']}")
        print(f"[OK] launcher: {result['exe']}")
        return
    print(f"[FAIL] {result.get('message', 'package failed')}")


def _safe_remove_dir(path: Path) -> None:
    resolved = path.resolve()
    exports = EXPORTS_DIR.resolve()
    if resolved == exports or exports not in resolved.parents:
        raise RuntimeError(f"refuse to remove a directory outside exports: {resolved}")
    if resolved.exists():
        shutil.rmtree(resolved)


def _ensure_godot_ignored_process_dirs() -> None:
    for name in GODOT_IGNORE_DIRS:
        directory = PROJECT_ROOT / name
        directory.mkdir(parents=True, exist_ok=True)
        marker = directory / ".gdignore"
        if not marker.exists():
            marker.write_text("# Generated by scripts/package_windows.py\n", encoding="utf-8")


def _find_template_package() -> Path:
    candidates = sorted(
        (PROJECT_ROOT / "tools").glob("Godot_v*_export_templates.tpz"),
        key=lambda path: path.stat().st_mtime,
        reverse=True,
    )
    for candidate in candidates:
        try:
            with zipfile.ZipFile(candidate) as zf:
                if TEMPLATE_ENTRY in zf.namelist():
                    return candidate
        except zipfile.BadZipFile:
            continue
    raise RuntimeError("windows export template was not found in tools/Godot_v*_export_templates.tpz")


def _extract_windows_template(template_package: Path, exe_path: Path) -> None:
    exe_path.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(template_package) as zf:
        with zf.open(TEMPLATE_ENTRY) as source, exe_path.open("wb") as target:
            shutil.copyfileobj(source, target)


def _export_windows_release(godot: str, exe_path: Path) -> None:
    command = [godot, "--headless", "--export-release", EXPORT_PRESET, str(exe_path)]
    result = subprocess.run(
        command,
        cwd=PROJECT_ROOT,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
    )
    if result.returncode != 0:
        message = (result.stderr or result.stdout or "godot Windows export failed").strip()
        raise RuntimeError(message)
    pck_path = exe_path.with_suffix(".pck")
    if not exe_path.exists() or exe_path.stat().st_size <= 0:
        raise RuntimeError(f"Windows export succeeded but exe was not created: {exe_path}")
    if not pck_path.exists() or pck_path.stat().st_size <= 0:
        raise RuntimeError(f"Windows export succeeded but pck was not created: {pck_path}")


def _verify_exported_exe(exe_path: Path) -> str:
    result = subprocess.run(
        [str(exe_path), "--headless", "--quit-after", "1"],
        cwd=exe_path.parent,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        timeout=30,
    )
    output = (result.stdout + "\n" + result.stderr).strip()
    if result.returncode != 0:
        raise RuntimeError(output or f"exported exe exited with {result.returncode}")
    return output


def _zip_directory(source_dir: Path, zip_path: Path) -> tuple[int, int]:
    file_count = 0
    zip_path.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=9) as zf:
        for path in sorted(source_dir.rglob("*")):
            if not path.is_file():
                continue
            arcname = Path(source_dir.name) / path.relative_to(source_dir)
            zf.write(path, arcname.as_posix())
            file_count += 1
    return file_count, zip_path.stat().st_size // 1024


def build_package(
    out_dir: Path,
    zip_path: Path,
    game_name: str,
    godot_arg: str,
    no_zip: bool,
    no_verify: bool,
) -> dict[str, Any]:
    godot = find_godot(godot_arg)
    if not godot:
        raise RuntimeError("Godot executable was not found. Run init.cmd or pass --godot.")

    _ensure_godot_ignored_process_dirs()
    template_package = _find_template_package()
    _extract_windows_template(template_package, WINDOWS_TEMPLATE)
    _safe_remove_dir(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    exe_path = out_dir / f"{game_name}.exe"
    pck_path = out_dir / f"{game_name}.pck"
    _export_windows_release(godot, exe_path)
    (out_dir / "README.txt").write_text(README_CONTENT, encoding="utf-8", newline="\r\n")

    verify_output = ""
    if not no_verify:
        verify_output = _verify_exported_exe(exe_path)

    zip_result = ""
    zip_size_kb = 0
    zip_file_count = 0
    if not no_zip:
        if zip_path.exists():
            zip_path.unlink()
        zip_file_count, zip_size_kb = _zip_directory(out_dir, zip_path)
        zip_result = str(zip_path)

    return {
        "status": "ok",
        "out_dir": str(out_dir),
        "zip": zip_result,
        "zip_size_kb": zip_size_kb,
        "zip_file_count": zip_file_count,
        "exe": str(exe_path),
        "pck": str(pck_path),
        "pck_size_kb": pck_path.stat().st_size // 1024,
        "template_package": str(template_package),
        "verify": "skipped" if no_verify else "ok",
        "verify_output_tail": verify_output[-1000:],
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Build a native Windows playable package.")
    parser.add_argument("--out-dir", default=str(DEFAULT_OUT_DIR), help="Output directory.")
    parser.add_argument("--zip", dest="zip_path", default=str(DEFAULT_ZIP), help="Zip output path.")
    parser.add_argument("--game-name", default=DEFAULT_GAME_NAME, help="Exe and pck base name.")
    parser.add_argument("--godot", default="", help="Godot executable path.")
    parser.add_argument("--no-zip", action="store_true", help="Only create the directory.")
    parser.add_argument("--no-verify", action="store_true", help="Skip exported exe headless smoke check.")
    parser.add_argument("--json", action="store_true", help="Print JSON.")
    args = parser.parse_args()

    out_dir = Path(args.out_dir)
    if not out_dir.is_absolute():
        out_dir = PROJECT_ROOT / out_dir
    zip_path = Path(args.zip_path)
    if not zip_path.is_absolute():
        zip_path = PROJECT_ROOT / zip_path

    try:
        result = build_package(
            out_dir=out_dir,
            zip_path=zip_path,
            game_name=args.game_name,
            godot_arg=args.godot,
            no_zip=args.no_zip,
            no_verify=args.no_verify,
        )
    except Exception as exc:
        _print({"status": "error", "message": str(exc)}, args.json)
        return 1

    _print(result, args.json)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
